EC2:
  GroupName: EX2-group
  Description: EX2
  KeyName: ex2-keypair
  ImageId: ami-007855ac798b5175e
  InstanceType: t2.micro
  MinCount: 1
  MaxCount: 1
  region: us-east-1
  RoleName: ex2-role

Commands:
  - sudo apt-get update
  - sudo apt-get install -y python3-pip git
  - git clone https://github.com/DorSkoler/cloud-ex2.git
  - cd cloud-ex2 && git pull
  - sudo pip3 install -r cloud-ex2/requirements.txt
  - nohup sudo python3 cloud-ex2/app.py --port 5000 > app.log 2>&1 &
  - echo Running Application

CommandsWorker:
  - sudo apt-get update
  - sudo apt-get install -y python3-pip git
  - git clone https://github.com/DorSkoler/cloud-ex2.git
  - cd cloud-ex2 && git pull
  - sudo pip3 install -r cloud-ex2/requirements.txt
  - nohup sudo python3 cloud-ex2/worker.py --port 5000 > worker.log 2>&1 &
  - echo Running Application
